## Filtros por Linhas e Colunas

In [12]:
import numpy as np 
import pandas as pd

In [54]:
dfCanada = pd.read_excel('https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DV0101EN-SkillsNetwork/Data%20Files/Canada.xlsx', sheet_name='Canada by Citizenship', skiprows=range(20), skipfooter=2)
dfCanada.rename(columns={'OdName':'Country', 'AreaName':'Continent', 'RegName':'Region'}, inplace=True)
dfCanada.columns = list(map(str, dfCanada.columns))

In [55]:
dfCanada.head()

,Type,Coverage,Country,AREA,Continent,REG,Region,DEV,DevName,1980,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
0,Immigrants,Foreigners,Afghanistan,935,Asia,5501,Southern Asia,902,Developing regions,16,...,2978,3436,3009,2652,2111,1746,1758,2203,2635,2004
1,Immigrants,Foreigners,Albania,908,Europe,925,Southern Europe,901,Developed regions,1,...,1450,1223,856,702,560,716,561,539,620,603
2,Immigrants,Foreigners,Algeria,903,Africa,912,Northern Africa,902,Developing regions,80,...,3616,3626,4807,3623,4005,5393,4752,4325,3774,4331
3,Immigrants,Foreigners,American Samoa,909,Oceania,957,Polynesia,902,Developing regions,0,...,0,0,1,0,0,0,0,0,0,0
4,Immigrants,Foreigners,Andorra,908,Europe,925,Southern Europe,901,Developed regions,0,...,0,0,1,1,0,0,0,0,1,1

### Selecionar coluna

** Existem duas maneiras de filtrar o nome de uma coluna: **

Método 1: rápido e fácil, mas só funciona se o nome da coluna NÃO tiver espaços ou caracteres especiais.

```python
     df.column_name
         (retorna a série)
```

Método 2: mais robusto e pode filtrar em várias colunas.

```python
     df ['coluna']
         (retorna a série)
```

```python
     df [['coluna 1', 'coluna 2']]
         (retorna dataframe)
```

* * *

In [56]:
dfCanada.Country

0         Afghanistan
1             Albania
2             Algeria
3      American Samoa
4             Andorra
            ...
190          Viet Nam
191    Western Sahara
192             Yemen
193            Zambia
194          Zimbabwe
Name: Country, Length: 195, dtype: object

In [57]:
dfCanada[['Country', '1980', '1981', '1982', '1983', '1984', '1985']]

            Country  1980  1981  1982  1983  1984  1985
0       Afghanistan    16    39    39    47    71   340
1           Albania     1     0     0     0     0     0
2           Algeria    80    67    71    69    63    44
3    American Samoa     0     1     0     0     0     0
4           Andorra     0     0     0     0     0     0
..              ...   ...   ...   ...   ...   ...   ...
190        Viet Nam  1191  1829  2162  3404  7583  5907
191  Western Sahara     0     0     0     0     0     0
192           Yemen     1     2     1     6     0    18
193          Zambia    11    17    11     7    16     9
194        Zimbabwe    72   114   102    44    32    29

[195 rows x 7 columns]

### Selecione a linha

Existem duas maneiras principais de selecionar linhas:

```python
     df.loc [rótulo]
         #filtros pelos rótulos do índice / coluna
     df.iloc [index]
         #filtros pelas posições do índice / coluna
```

Antes de prosseguirmos, observe que o índice padrão do conjunto de dados é um intervalo numérico de 0 a 194. Isso torna muito difícil fazer uma consulta por um país específico. Por exemplo, para pesquisar dados sobre o Japão, precisamos saber o valor do índice correspondente.

Isso pode ser corrigido facilmente definindo a coluna 'País' como o índice usando o método `set_index ()`.

In [58]:
dfCanada.set_index('Country', inplace=True)

In [59]:
dfCanada.head()

,Type,Coverage,AREA,Continent,REG,Region,DEV,DevName,1980,1981,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
Country,,,,,,,,,,,,,,,,,,,,,
Afghanistan,Immigrants,Foreigners,935,Asia,5501,Southern Asia,902,Developing regions,16,39,...,2978,3436,3009,2652,2111,1746,1758,2203,2635,2004
Albania,Immigrants,Foreigners,908,Europe,925,Southern Europe,901,Developed regions,1,0,...,1450,1223,856,702,560,716,561,539,620,603
Algeria,Immigrants,Foreigners,903,Africa,912,Northern Africa,902,Developing regions,80,67,...,3616,3626,4807,3623,4005,5393,4752,4325,3774,4331
American Samoa,Immigrants,Foreigners,909,Oceania,957,Polynesia,902,Developing regions,0,1,...,0,0,1,0,0,0,0,0,0,0
Andorra,Immigrants,Foreigners,908,Europe,925,Southern Europe,901,Developed regions,0,0,...,0,0,1,1,0,0,0,0,1,1

In [60]:
dfCanada.index.name = None

In [61]:
dfCanada.head()

,Type,Coverage,AREA,Continent,REG,Region,DEV,DevName,1980,1981,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
Afghanistan,Immigrants,Foreigners,935,Asia,5501,Southern Asia,902,Developing regions,16,39,...,2978,3436,3009,2652,2111,1746,1758,2203,2635,2004
Albania,Immigrants,Foreigners,908,Europe,925,Southern Europe,901,Developed regions,1,0,...,1450,1223,856,702,560,716,561,539,620,603
Algeria,Immigrants,Foreigners,903,Africa,912,Northern Africa,902,Developing regions,80,67,...,3616,3626,4807,3623,4005,5393,4752,4325,3774,4331
American Samoa,Immigrants,Foreigners,909,Oceania,957,Polynesia,902,Developing regions,0,1,...,0,0,1,0,0,0,0,0,0,0
Andorra,Immigrants,Foreigners,908,Europe,925,Southern Europe,901,Developed regions,0,0,...,0,0,1,1,0,0,0,0,1,1

Exemplo: vamos ver o número de imigrantes do Japão (linha 87) para os seguintes cenários:

```
1. Os dados da linha completa (todas as colunas)
2. Para o ano de 2013
3. Durante os anos 1980 a 1985
```

In [62]:
# 1. the full row data (all columns)
#print(dfCanada.loc['Japan'])

# alternate methods
#print(dfCanada.iloc[87])
print(dfCanada[dfCanada.index == 'Japan'].squeeze())

Type                Immigrants
Coverage            Foreigners
AREA                       935
Continent                 Asia
REG                        906
Region            Eastern Asia
DEV                        901
DevName      Developed regions
1980                       701
1981                       756
1982                       598
1983                       309
1984                       246
1985                       198
1986                       248
1987                       422
1988                       324
1989                       494
1990                       379
1991                       506
1992                       605
1993                       907
1994                       956
1995                       826
1996                       994
1997                       924
1998                       897
1999                      1083
2000                      1010
2001                      1092
2002                       806
2003                       817
2004                       973
2005                      1067
2006                      1212
2007                      1250
2008                      1284
2009                      1194
2010                      1168
2011                      1265
2012                      1214
2013                       982
Name: Japan, dtype: object

In [63]:
# 2. for year 2013
#print(dfCanada.loc['Japan', '2013'])

# alternate method
print(dfCanada.iloc[87, 41]) # year 2013 is the last column, with a positional index of 41

982

In [66]:
# 3. for years 1980 to 1985
#print(dfCanada.loc['Japan', ['1980', '1981', '1982', '1983', '1984', '1985']])
print(dfCanada.iloc[87, [3, 4, 5, 6, 7, 8]])

Continent                 Asia
REG                        906
Region            Eastern Asia
DEV                        901
DevName      Developed regions
1980                       701
Name: Japan, dtype: object

### Filtragem com base em um critério

Para filtrar o dataframe com base em uma condição, simplesmente passamos a condição como um vetor booleano.

Por exemplo, vamos filtrar o dataframe para mostrar os dados em países asiáticos (AreaName = Asia).

In [68]:
# 1. create the condition boolean series
condition = dfCanada['Continent'] == 'Asia'

In [69]:
dfCanada[condition]

,Type,Coverage,AREA,Continent,REG,Region,DEV,DevName,1980,1981,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
Afghanistan,Immigrants,Foreigners,935,Asia,5501,Southern Asia,902,Developing regions,16,39,...,2978,3436,3009,2652,2111,1746,1758,2203,2635,2004
Armenia,Immigrants,Foreigners,935,Asia,922,Western Asia,902,Developing regions,0,0,...,147,224,218,198,205,267,252,236,258,207
Azerbaijan,Immigrants,Foreigners,935,Asia,922,Western Asia,902,Developing regions,0,0,...,230,359,236,203,125,165,209,138,161,57
Bahrain,Immigrants,Foreigners,935,Asia,922,Western Asia,902,Developing regions,0,2,...,12,12,12,22,9,35,28,21,39,32
Bangladesh,Immigrants,Foreigners,935,Asia,5501,Southern Asia,902,Developing regions,83,84,...,2660,4171,4014,2897,2939,2104,4721,2694,2640,3789
Bhutan,Immigrants,Foreigners,935,Asia,5501,Southern Asia,902,Developing regions,0,0,...,1,5,10,7,36,865,1464,1879,1075,487
Brunei Darussalam,Immigrants,Foreigners,935,Asia,920,South-Eastern Asia,902,Developing regions,79,6,...,3,4,5,11,10,5,12,6,3,6
Cambodia,Immigrants,Foreigners,935,Asia,920,South-Eastern Asia,902,Developing regions,12,19,...,348,370,529,460,354,203,200,196,233,288
China,Immigrants,Foreigners,935,Asia,906,Eastern Asia,902,Developing regions,5123,6682,...,36619,42584,33518,27642,30037,29622,30391,28502,33024,34129
"China, Hong Kong Special Administrative Region",Immigrants,Foreigners,935,Asia,906,Eastern Asia,902,Developing regions,0,0,...,536,729,712,674,897,657,623,591,728,774
"China, Macao Special Administrative Region",Immigrants,Foreigners,935,Asia,906,Eastern Asia,902,Developing regions,0,0,...,21,21,32,16,12,21,21,13,33,29
Cyprus,Immigrants,Foreigners,935,Asia,922,Western Asia,902,Developing regions,132,128,...,11,7,9,4,7,6,18,6,12,16
Democratic People's Republic of Korea,Immigrants,Foreigners,935,Asia,906,Eastern Asia,902,Developing regions,1,1,...,15,14,10,7,19,11,45,97,66,17
Georgia,Immigrants,Foreigners,935,Asia,922,Western Asia,902,Developing regions,0,0,...,106,114,125,132,112,128,126,139,147,125
India,Immigrants,Foreigners,935,Asia,5501,Southern Asia,902,Developing regions,8880,8670,...,28235,36210,33848,28742,28261,29456,34235,27509,30933,33087
Indonesia,Immigrants,Foreigners,935,Asia,920,South-Eastern Asia,902,Developing regions,186,178,...,552,632,613,657,661,504,712,390,395,387
Iran (Islamic Republic of),Immigrants,Foreigners,935,Asia,5501,Southern Asia,902,Developing regions,1172,1429,...,6348,5837,7480,6974,6475,6580,7477,7479,7534,11291
Iraq,Immigrants,Foreigners,935,Asia,922,Western Asia,902,Developing regions,262,245,...,1796,2226,1788,2406,3543,5450,5941,6196,4041,4918
Israel,Immigrants,Foreigners,935,Asia,922,Western Asia,902,Developing regions,1403,1711,...,2788,2446,2625,2401,2562,2316,2755,1970,2134,1945
Japan,Immigrants,Foreigners,935,Asia,906,Eastern Asia,901,Developed regions,701,756,...,973,1067,1212,1250,1284,1194,1168,1265,1214,982
Jordan,Immigrants,Foreigners,935,Asia,922,Western Asia,902,Developing regions,177,160,...,1733,1940,1827,1421,1581,1235,1831,1635,1206,1255
Kazakhstan,Immigrants,Foreigners,935,Asia,5500,Central Asia,902,Developing regions,0,0,...,545,506,408,436,394,431,377,381,462,348
Kuwait,Immigrants,Foreigners,935,Asia,922,Western Asia,902,Developing regions,1,0,...,74,66,35,62,53,68,67,58,73,48
Kyrgyzstan,Immigrants,Foreigners,935,Asia,5500,Central Asia,902,Developing regions,0,0,...,245,173,161,135,168,173,157,159,278,123
Lao People's Democratic Republic,Immigrants,Foreigners,935,Asia,920,South-Eastern Asia,902,Developing regions,11,6,...,38,42,74,53,32,39,54,22,25,15
Lebanon,Immigrants,Foreigners,935,Asia,922,Western Asia,902,Developing regions,1409,1119,...,3293,3709,3802,3467,3566,3077,3432,3072,1614,2172
Malaysia,Immigrants,Foreigners,935,Asia,920,South-Eastern Asia,902,Developing regions,786,816,...,401,593,580,600,658,640,802,409,358,204
Maldives,Immigrants,Foreigners,935,Asia,5501,Southern Asia,902,Developing regions,0,0,...,1,0,0,2,1,7,4,3,1,1
Mongolia,Immigrants,Foreigners,935,Asia,906,Eastern Asia,902,Developing regions,0,0,...,34,59,64,82,59,118,169,103,68,99
Myanmar,Immigrants,Foreigners,935,Asia,920,South-Eastern Asia,902,Developing regions,80,62,...,191,210,953,1887,975,1153,556,368,193,262
Nepal,Immigrants,Foreigners,935,Asia,5501,Southern Asia,902,Developing regions,1,1,...,404,607,540,511,581,561,1392,1129,1185,1308
Oman,Immigrants,Foreigners,935,Asia,922,Western Asia,902,Developing regions,0,0,...,12,14,18,16,10,7,14,10,13,11
Pakistan,Immigrants,Foreigners,935,Asia,5501,Southern Asia,902,Developing regions,978,972,...,13399,14314,13127,10124,8994,7217,6811,7468,11227,12603
Philippines,Immigrants,Foreigners,935,Asia,920,South-Eastern Asia,902,Developing regions,6051,5921,...,14004,18139,18400,19837,24887,28573,38617,36765,34315,29544
Qatar,Immigrants,Foreigners,935,Asia,922,Western Asia,902,Developing regions,0,0,...,5,11,2,5,9,6,18,3,14,6
Republic of Korea,Immigrants,Foreigners,935,Asia,906,Eastern Asia,902,Developing regions,1011,1456,...,5352,5832,6215,5920,7294,5874,5537,4588,5316,4509
Saudi Arabia,Immigrants,Foreigners,935,Asia,922,Western Asia,902,Developing regions,0,0,...,128,198,252,188,249,246,330,278,286,267
Singapore,Immigrants,Foreigners,935,Asia,920,South-Eastern Asia,902,Developing regions,241,301,...,311,392,298,690,734,366,805,219,146,141
Sri Lanka,Immigrants,Foreigners,935,Asia,5501,Southern Asia,902,Developing regions,185,371,...,4495,4930,4714,4123,4756,4547,4422,3309,3338,2394
State of Palestine,Immigrants,Foreigners,935,Asia,922,Western Asia,902,Developing regions,0,0,...,376,453,627,441,481,400,654,555,533,462
Syrian Arab Republic,Immigrants,Foreigners,935,Asia,922,Western Asia,902,Developing regions,315,419,...,1116,1458,1145,1056,919,917,1039,1005,650,1009
Tajikistan,Immigrants,Foreigners,935,Asia,5500,Central Asia,902,Developing regions,0,0,...,14,85,46,44,15,50,52,47,34,39
Thailand,Immigrants,Foreigners,935,Asia,920,South-Eastern Asia,902,Developing regions,56,53,...,392,575,500,487,519,512,499,396,296,400
Turkey,Immigrants,Foreigners,935,Asia,922,Western Asia,902,Developing regions,481,874,...,1736,2065,1638,1463,1122,1238,1492,1257,1068,729
Turkmenistan,Immigrants,Foreigners,935,Asia,5500,Central Asia,902,Developing regions,0,0,...,16,40,26,37,13,20,30,20,20,14
United Arab Emirates,Immigrants,Foreigners,935,Asia,922,Western Asia,902,Developing regions,0,2,...,41,31,42,37,33,37,86,60,54,46
Uzbekistan,Immigrants,Foreigners,935,Asia,5500,Central Asia,902,Developing regions,0,0,...,175,330,262,284,215,288,289,162,235,167
Viet Nam,Immigrants,Foreigners,935,Asia,920,South-Eastern Asia,902,Developing regions,1191,1829,...,1816,1852,3153,2574,1784,2171,1942,1723,1731,2112
Yemen,Immigrants,Foreigners,935,Asia,922,Western Asia,902,Developing regions,1,2,...,124,161,140,122,133,128,211,160,174,217

In [71]:
# podemos passar vários critérios na mesma linha.
# vamos filtrar por AreaNAme = Asia e RegName = 

dfCanada[(dfCanada['Continent'] == 'Asia') & (dfCanada['Region'] == 'Southern Asia')]

# nota: ao usar os operadores 'e' e 'ou', o pandas requer o uso de '&' e '|' em vez de 'e' e 'ou'
# não se esqueça de colocar as duas condições entre parênteses

,Type,Coverage,AREA,Continent,REG,Region,DEV,DevName,1980,1981,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
Afghanistan,Immigrants,Foreigners,935,Asia,5501,Southern Asia,902,Developing regions,16,39,...,2978,3436,3009,2652,2111,1746,1758,2203,2635,2004
Bangladesh,Immigrants,Foreigners,935,Asia,5501,Southern Asia,902,Developing regions,83,84,...,2660,4171,4014,2897,2939,2104,4721,2694,2640,3789
Bhutan,Immigrants,Foreigners,935,Asia,5501,Southern Asia,902,Developing regions,0,0,...,1,5,10,7,36,865,1464,1879,1075,487
India,Immigrants,Foreigners,935,Asia,5501,Southern Asia,902,Developing regions,8880,8670,...,28235,36210,33848,28742,28261,29456,34235,27509,30933,33087
Iran (Islamic Republic of),Immigrants,Foreigners,935,Asia,5501,Southern Asia,902,Developing regions,1172,1429,...,6348,5837,7480,6974,6475,6580,7477,7479,7534,11291
Maldives,Immigrants,Foreigners,935,Asia,5501,Southern Asia,902,Developing regions,0,0,...,1,0,0,2,1,7,4,3,1,1
Nepal,Immigrants,Foreigners,935,Asia,5501,Southern Asia,902,Developing regions,1,1,...,404,607,540,511,581,561,1392,1129,1185,1308
Pakistan,Immigrants,Foreigners,935,Asia,5501,Southern Asia,902,Developing regions,978,972,...,13399,14314,13127,10124,8994,7217,6811,7468,11227,12603
Sri Lanka,Immigrants,Foreigners,935,Asia,5501,Southern Asia,902,Developing regions,185,371,...,4495,4930,4714,4123,4756,4547,4422,3309,3338,2394